name: Push and Pull request for Teams

on:
  push: 
    branches:
      - dub
  pull_request:
    branches:
      - main

jobs:
  check-duplicates:
    runs-on: ubuntu-latest
    steps:
      - name: Make the script files executable
        run: chmod +x duplicates.sh
      - name: Run the scripts
        run: ./dup_test/duplicates.sh